// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeohzX1kRsXK3LZVXYdeU58mfY1PVX0aE',
    appId: '1:896459730176:android:11c743e2aba0d8cdaa57e5',
    messagingSenderId: '896459730176',
    projectId: 'scrumflow-c835d',
    storageBucket: 'scrumflow-c835d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHMS_wlvJ_A568HvxCNV9beRLcxw1DaY4',
    appId: '1:896459730176:ios:0b74cc1fb0eb546aaa57e5',
    messagingSenderId: '896459730176',
    projectId: 'scrumflow-c835d',
    storageBucket: 'scrumflow-c835d.firebasestorage.app',
    iosBundleId: 'com.scrumflow.scrumflow',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxcDHlYqEpST08GEfwKErnpHE9TyfTcSE',
    appId: '1:896459730176:web:2085017886be5042aa57e5',
    messagingSenderId: '896459730176',
    projectId: 'scrumflow-c835d',
    authDomain: 'scrumflow-c835d.firebaseapp.com',
    storageBucket: 'scrumflow-c835d.firebasestorage.app',
  );
}
